# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: CI

on:
  push:
    branches: [master, '*']
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Install Chrome
      run: sudo apt install google-chrome-stable
    - name: Cache Gradle packages
      uses: actions/cache@v1
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
        restore-keys: ${{ runner.os }}-gradle
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      env:
        SPOTIFY_USERNAME: ${{ secrets.SPOTIFYUSERNAME }}
        SPOTIFY_PASSWORD: ${{ secrets.SPOTIFYPASSWORD }}
        SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFYCLIENTID }}
        SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFYCLIENTSECRET }}
      run: >
        ./gradlew build -Pspotify.username="$SPOTIFY_USERNAME" -Pspotify.password="$SPOTIFY_PASSWORD"
        -Pspotify.client.id="$SPOTIFY_CLIENT_ID" -Pspotify.client.secret="$SPOTIFY_CLIENT_SECRET"
        -PexcludeTests="**/CommandLineSpotifyAdvisorEndToEndTest*" --info
    - name: Publish Unit Test Results
      uses: EnricoMi/publish-unit-test-result-action@v1.7
      if: always()
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        files: build/test-results/**/*.xml
